[package]
name = "bce_exchange_client"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/client.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
http-client.workspace = true
serde.workspace = true
