[package]
name = "bce_exchange_database_sqlite"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/sqlite.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bce_exchange_database.workspace = true
chrono.workspace = true
serde_json.workspace = true
sqlx.workspace = true
